### ISSUE TITLE
为什么post方法无法进入Handler处理程序

### ISSUE THREAD

**Issue by LionMiao** [kklldog/AServer#5]
如下图，GET测试正常，POST无法进入处理程序，但控制台会打印post请求的路径。
![image](https://user-images.githubusercontent.com/3351903/84626039-facb7300-af16-11ea-9ef2-224e1c23de3c.png)

**Comment by kklldog** [comment]
你用的是chrome的postman x件吧，这个插件会有跨域的问题，它的请求都携带了一个header origin=chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop类似这种，testserver配置的跨域origin是localhost5000所以匹配不上，直接返回200ok，可能是我这个code比较误导，后面考虑改个错误的代码。想要测试你需要使用postman app ，非插件版的。
