### ISSUE TITLE
worker service 项目中使用异常

### ISSUE THREAD

**Issue by dodu2014** [kklldog/AServer#9]
Object reference not set to an instance of an object.

StackTrace:

   在 Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.CreateResponseHeader(Boolean appCompleted)
   在 Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.InitializeResponseAsync(Int32 firstWriteByteCount)
   在 Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.WriteAsync(ReadOnlyMemory`1 data, CancellationToken cancellationToken)
   在 Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   在 Microsoft.AspNetCore.Http.HttpResponseWritingExtensions.WriteAsync(HttpResponse response, String text, Encoding encoding, CancellationToken cancellationToken)
   在 Microsoft.AspNetCore.Http.HttpResponseWritingExtensions.WriteAsync(HttpResponse response, String text, CancellationToken cancellationToken)

**Comment by kklldog** [comment]
能不能说的明白点，或者直接把代码推上来

**Comment by dodu2014** [comment]
示例：AServer.Test.Server

把sdk设置成：
`<Project Sdk="Microsoft.NET.Sdk.Worker">`
TargetFramework 是 net6.0

调用AServer就异常了，因为我这边的项目是基于 WorkerService，想使用 Aserver 提供 httpserver 服务。

**Comment by dodu2014** [comment]
能理解我说的吧，要不我把我建的worker service的demo发你邮箱 😊

补充一点，不是跑起来时异常，是跑起来后调用监听的url时，handler 中 response.Write 时异常

**Comment by kklldog** [comment]
> 能理解我说的吧，要不我把我建的worker service的demo发你邮箱 😊
> 
> 补充一点，不是跑起来时异常，是跑起来后调用监听的url时，handler 中 response.Write 时异常

可以，qq17014842 发邮箱也好直接加qq也行

**Comment by dodu2014** [comment]
刚加你qq，看你没响应，发你邮箱里了

**Comment by kklldog** [comment]
> 刚加你qq，看你没响应，发你邮箱里了

好，晚上看看

**Comment by kklldog** [comment]
我看了一下，Aserver里其实是使用了 2.2 的webhostbuilder 因为你已经使用了最新的 hostbuilder 所以对于http的处理已经被你拦截了，其实如果你使用net6的话，使用 miniapi 就可以了，AServer 在net6上面没有太多的意义 。

**Comment by dodu2014** [comment]
好的，gei到知识点，非常感谢！😊
